travis:
  secure:
    BINSTAR_TOKEN: A7cNsMkxtY2Jnj7DGMlr0xm5KmQTrVyrIpXpE7GiIy+Nu9bjFhcunWICogixHNNgrfBa4hc7CiLmUOn9mgGbBiR8sxrrBTPrMPFICVFKEiAWB7ez7mppsEpGUF7e4bRED4wU4wiu76xrUwtMII7bCA/dGc/+eGP453e2BwNKJVGvU2/sB+2qc9oXfF0H14Sv5FTKQ+gbFTs7nMhpzQ8DnGdmnDHHGxI70jvATvUhxV/DSnIYHGzpn4c3WOYDEJcUzCSsgcpCGKmkthTdTyohpoREM9646eWzOIrn67xgRvor6Le1Hm5oxL4m99URLoF+1e99HWHVXebcsWrFRi4/7HZkMcGQQoyTRbCgBj5wcvGjIyiMTl+0FuFMxxbKgao4e4MDYe6FGqHMSbcLMUO0rg4mTbCIlow7bxD0egRmNzB55fM9AIyUe66sAo3ENlmUBsAPiw5eZIyOAg1kojPsDlvcndKY6BxBJ9n80MKLFLrykWamXFAQZwg5yr7iTlOg/ao0a15K+zCSaCL+04qfMjaMkXatcQ5j+7h/15iS9drN6gfiiLd4FVOK3gpPbeJAQbe0vTP3v6ChLy+7RAtSgCvNbRw5D+SARCq99Z8+whJ2HzNqPkyMhn6g8lfdnXqwspky9UhT1LcFtHAA/yxoXdbipOGHxKgvjzW1AS1v31E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
